version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - password_1
      - password_2
  
  password_1:
    image: nicopaez/password-api
    
  password_2:
    image: nicopaez/password-api
    
